const proj = [
  {
    domain: "Python Programming",
    title: "Python Programming Fundamentals",
    duration: "4-6 weeks",
    overview: "Learn the fundamentals of Python programming language. Master the syntax, data types, control flow, and object-oriented programming concepts to build powerful and efficient applications.",
    Training_program_benefits: [
      	"Python programming live lectures (on the spot doubt clearance)",
      	"Basic and advanced python libraries",
      	"Game development lectures",
      	"Quizzes for self-assessment",
      	"Live lectures with coding",
      	"Project for performance evaluation (optional)",
      	"Opportunity for internship with AI-Shala",
      	"Certificate program" 
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
    Lectures: "16",
    starting: "Anytime",
    time: "Time: 3 months (flipped classroom)",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832218/Python_Programming_2_cb4pwo.jpg",
    Curriculum: [
      "The training program contains four modules in total, and the following is the description of each module.",
      "Module 1: Basic and Introduction to Python",
      "Module 2: Basic and Advanced data structures",
      "Module 3: Advanced libraries"
    ],
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832219/Python_Programming_1_blwivo.png"
  },
  {
    domain: "Machine Learning",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Machine Learning Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686909854/ML_3_r6zhnv.jpg",
    duration: "6-8 weeks",
    overview: "Explore the exciting field of machine learning. Gain hands-on experience with popular algorithms and techniques to train models that can make predictions and decisions based on data.",
    Training_program_benefits: [
      "Hands-on experience with popular ML algorithms and techniques",
      "Training models for predictions and decision-making based on data",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Optional project for practical application",
      "Opportunity for internship with AI-Shala",
      "Certificate program"
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Data Science",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686910242/3156627_htzu9s.jpg",
    king: "https://aishala.in/img/courses/course_details_thumb_dive-in.gif",
    title: "Data Science Fundamentals",
    duration: "8-10 weeks",
    overview: "Dive into the world of data science and learn the essential skills to extract insights from data. Discover data cleaning, visualization, statistical analysis, and machine learning to solve real-world problems.",
    Training_program_benefits: [
      "Essential skills for extracting insights from data",
      "Data cleaning, visualization, and statistical analysis",
      "Introduction to machine learning for solving real-world problems",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Optional project for practical application",
      "Opportunity for internship with AI-Shala",
      "Certificate program"   
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Linear Algebra",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Linear Algebra for Machine Learning",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "2-4 weeks",
    overview: "Develop a solid foundation in linear algebra, a fundamental mathematical framework for machine learning. Understand vectors, matrices, eigenvalues, and their applications in solving ML problems.",
    Training_program_benefits: [
      "Solid foundation in linear algebra for ML",
      "Understanding vectors, matrices, and eigenvalues",
      "Application of linear algebra in solving ML problems",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program"  
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Statistics",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Statistics Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Unlock the power of statistics for data analysis. Learn essential concepts like probability, hypothesis testing, regression analysis, and experimental design to make data-driven decisions.",
    Training_program_benefits: [
      "Unlocking the power of statistics for data analysis",
      "Concepts like probability, hypothesis testing, and regression analysis",
      "Experimental design for making data-driven decisions",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Deep Learning",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Deep Learning Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Delve into the realm of deep learning, a cutting-edge field of AI. Discover neural networks, convolutional and recurrent networks, and train models to tackle complex tasks like image recognition and natural language processing.",
    Training_program_benefits: [
      "Exploration of cutting-edge deep learning techniques",
      "Understanding neural networks, convolutional and recurrent networks",
      "Training models for complex tasks like image recognition and NLP",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Big Data",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Big Data, Hadoop, and Spark Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Harness the potential of big data technologies. Learn to process large datasets using Hadoop and utilize the power of Apache Spark for distributed data processing and analytics.",
    Training_program_benefits: [
      "Harnessing the potential of big data technologies",
      "Processing large datasets using Hadoop",
      "Utilizing Apache Spark for distributed data processing and analytics",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "PySpark",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "PySpark and Spark ML Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Master PySpark, the Python API for Apache Spark. Explore data manipulation, feature engineering, and machine learning with Spark MLlib to build scalable and efficient data pipelines.",
    Training_program_benefits: [
      "Mastering PySpark, the Python API for Spark",
      "Data manipulation, feature engineering, and ML with Spark MLlib",
      "Building scalable and efficient data pipelines",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program"
      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "C and C++",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "C and C++ Programming Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "8-10 weeks",
    overview: "Learn the foundational languages of C and C++. Gain expertise in programming concepts, memory management, and build essential skills for system-level development and performance-critical applications",
    Training_program_benefits: [
      "Learning foundational languages of C and C++",
      "Expertise in programming concepts and memory management",
      "Essential skills for system-level development and performance-critical applications",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Java Programming",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Java and Advanced Java Programming",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "8-10 weeks",
    overview: "Master Java, the versatile programming language used in a wide range of applications. Explore advanced topics like multithreading, networking, and database connectivity to build robust Java applications.",
    Training_program_benefits: [
      "Mastering the versatile programming language of Java",
      "Advanced topics like multithreading, networking, and database connectivity",
      "Building robust Java applications",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Certificate program"
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Flutter",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Mobile App Development with Flutter",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Build cross-platform mobile apps using Flutter framework. Learn Dart programming language, UI development, state management, and integration with backend services to create stunning mobile applications.",
    Training_program_benefits: [
      "Building cross-platform mobile apps using Flutter",
      "Learning Dart programming language",
      "UI development and state management",
      "Integration with backend services",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program"
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "DSA",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Data Structures and Algorithms",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "8-10 weeks",
    overview: "Develop a strong grasp of data structures and algorithms. Solve coding problems efficiently, implement common data structures, and optimize algorithms for better performance.",
    Training_program_benefits: [
      "Strong grasp of data structures and algorithms",
      "Efficient problem-solving and coding skills",
      "Implementation of common data structures",
      "Algorithm optimization for better performance",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Linux Administration",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Linux Administration",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Become proficient in Linux system administration. Learn essential commands, manage users and permissions, automate tasks with scripting, and troubleshoot common issues in a Linux environment.",
    Training_program_benefits: [
      "Proficiency in Linux system administration",
      "Essential commands and tasks automation with scripting",
      "User management, permissions, and troubleshooting",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Operating Systems",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Fundamentals of Operating Systems",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Gain a comprehensive understanding of operating systems. Explore process management, memory allocation, file systems, and security concepts to comprehend the core principles of modern operating systems.",
    Training_program_benefits: [
      "Comprehensive understanding of operating systems",
      "Process management, memory allocation, and file systems",
      "Security concepts and principles",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Data Analysis and Visualization",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Python Libraries for Data Analysis and Visualization",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Master essential Python libraries for data analysis and visualization. Utilize Pandas and NumPy for data manipulation, and create stunning visualizations with Plotly, Bokeh, and Matplotlib.",
    Training_program_benefits: [
      "Mastering essential Python libraries for data analysis and visualization",
      "Data manipulation with Pandas and NumPy",
      "Creating stunning visualizations with Plotly, Bokeh, and Matplotlib",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Computer Vision",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Computer Vision Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Enter the exciting world of computer vision. Learn image processing techniques, feature extraction, and deep learning algorithms to analyze and understand visual data.",
    Training_program_benefits: [
      "Entering the exciting world of computer vision",
      "Image processing techniques and feature extraction",
      "Deep learning algorithms for visual data analysis",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Natural Language Processing",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Natural Language Processing Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Dive into natural language processing and understand human language with the help of computers. Explore text preprocessing, sentiment analysis, and language modeling to build powerful NLP applications.",
    Training_program_benefits: [
      "Diving into natural language processing",
      "Text preprocessing and sentiment analysis",
      "Language modeling and text generation",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Image Processing",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Image Processing and Computer Vision",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Discover the techniques to process and analyze digital images. Gain insights into image enhancement, object recognition, and pattern recognition using computer vision algorithms.",
    Training_program_benefits: [
      "Techniques for processing and analyzing digital images",
      "Image enhancement, object recognition, and pattern recognition",
      "Computer vision algorithms for visual data interpretation",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Internet of Things",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Time Series and IoT Data Analytics",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Learn the art of analyzing time series and IoT data. Explore methods for forecasting, anomaly detection, and extracting valuable insights from time-dependent data in various IoT applications.",
    Training_program_benefits: [
      "Art of analyzing time series and IoT data",
      "Forecasting, anomaly detection, and insights extraction",
      "Applications in various IoT domains",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Github",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Industrialization with GitHub and CI/CD Pipelines",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "2-4 weeks",
    overview: "Learn industry best practices for software development. Utilize Git for version control, set up CI/CD pipelines for automated testing and deployment, and streamline the development process.",
    Training_program_benefits: [
      "Industry best practices for software development",
      "Version control with Git",
      "CI/CD pipelines for automated testing and deployment",
      "Streamlining the development process",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program"
      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Database Management Systems",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Database Management Systems (DBMS) with Oracle and MySQL",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview: "Master the fundamentals of database management systems. Learn SQL programming, data modeling, and gain hands-on experience with Oracle and MySQL databases.",
    Training_program_benefits: [
      "Fundamentals of database management systems",
      "SQL programming and data modeling",
      "Hands-on experience with Oracle and MySQL databases",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program"
      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "MongoDB and Firebase",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "MongoDB and Firebase for Modern Data Management",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview: "Explore modern NoSQL databases like MongoDB and Firebase. Learn to model data, perform CRUD operations, and integrate these databases into your applications for scalability and real-time capabilities.",
    Training_program_benefits: [
      "Exploring modern NoSQL databases like MongoDB and Firebase",
      "Data modeling and CRUD operations",
      "Integration into applications for scalability and real-time capabilities",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program"      
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  }
];

export default proj;
