const proj = [
  {
    domain: "Python Programming",
    title: "Python Programming Fundamentals",
    duration: "4-6 weeks",
    overview:
      "Learn the fundamentals of Python programming language. Master the syntax, data types, control flow, and object-oriented programming concepts to build powerful and efficient applications.",
    Training_program_benefits: [
      "Python programming live lectures (on the spot doubt clearance)",
      "Basic and advanced python libraries",
      "Game development lectures",
      "Quizzes for self-assessment",
      "Live lectures with coding",
      "Project for performance evaluation (optional)",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
    Lectures: "16",
    starting: "Anytime",
    time: "Time: 3 months (flipped classroom)",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832218/Python_Programming_2_cb4pwo.jpg",
    Curriculum: [
      "Module 1: Basic and Introduction to Python\n\nOverview of Python and its features\nSetting up the Python development environment\nRunning Python scripts and interactive sessions\nUnderstanding variables, data types, and basic operations",
      "Module 2: Basic and Advanced data structures\n\nWorking with lists, tuples, and dictionaries\nAccessing, modifying, and manipulating data within data structures\nExploring built-in functions and methods for data structure operations\nUnderstanding the concept of mutability and immutability",
      "Module 3: Advanced libraries\n\nExploring commonly used Python libraries (e.g., NumPy, Pandas, Matplotlib)\nInstalling and importing external modules\nLeveraging libraries for data analysis, visualization, and more\nOverview of popular Python frameworks and their applications",
      "Module 4: Object-Oriented Programming (OOP) in Python\n\nUnderstanding the principles and concepts of object-oriented programming\nCreating classes, objects, and attributes\nImplementing methods and encapsulation\nExploring inheritance, polymorphism, and abstraction in Python",
      "Module 5: File Handling and Input/Output Operations\n\nReading and writing data to files using Python\nHandling different file formats (e.g., text files, CSV, JSON)\nManaging file resources and working with file pointers\nParsing and processing data from files efficiently",
      "Module 6: Exception Handling and Error Management\n\nUnderstanding exceptions and their role in Python programs\nUsing try-except blocks for error handling and graceful program execution\nHandling specific exceptions and multiple exception types\nUtilizing the finally block for cleanup operations",
      "Module 7: Advanced Topics in Python\n\nExploring advanced concepts and techniques in Python programming\nWorking with generators and iterators for efficient memory usage\nUnderstanding decorators and their applications\nIntroduction to multithreading and multiprocessing in Python",
      "Module 8: Web Development with Python\n\nIntroduction to web development using Python\nBuilding web applications using frameworks such as Flask or Django\nHandling HTTP requests and responses\nIntegrating databases and creating dynamic web pages",
      "Module 9: Data Analysis and Visualization\n\nAdvanced data manipulation and analysis using libraries such as Pandas\nExploratory data analysis and data cleaning techniques\nData visualization using Matplotlib, Seaborn, or Plotly\nApplying statistical analysis and generating insights from data",
      "Module 10: Machine Learning with Python\n\nIntroduction to machine learning concepts and algorithms\nUtilizing popular machine learning libraries like Scikit-learn\nData preprocessing, feature engineering, and model evaluation\nBuilding and training machine learning models for various tasks",
    ],
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832219/Python_Programming_1_blwivo.png",
  },
  {
    domain: "Machine Learning",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Machine Learning Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686909854/ML_3_r6zhnv.jpg",
    duration: "6-8 weeks",
    overview:
      "Explore the exciting field of machine learning. Gain hands-on experience with popular algorithms and techniques to train models that can make predictions and decisions based on data.",
    Training_program_benefits: [
      "Hands-on experience with popular ML algorithms and techniques",
      "Training models for predictions and decision-making based on data",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Optional project for practical application",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Machine Learning\n\nUnderstanding the basics of machine learning and its applications\nDifferentiating between supervised, unsupervised, and reinforcement learning\nExploring real-world examples and case studies of machine learning",
      "Module 2: Data Pre-processing and Exploratory Data Analysis (EDA)\n\nCleaning and pre-processing raw data for machine learning\nHandling missing data and outliers\nVisualizing and analyzing data using statistical techniques\nFeature scaling and normalization",
      "Module 3: Supervised Learning Algorithms\n\nLinear regression and logistic regression for regression and classification tasks\nDecision trees and random forests for classification and regression\nSupport Vector Machines (SVM) for binary and multi-class classification\nEvaluating model performance using metrics like accuracy, precision, recall, and F1-score",
      "Module 4: Unsupervised Learning Algorithms\n\nK-means clustering for grouping similar data points\nHierarchical clustering for creating clusters based on data structure\nDimensionality reduction techniques such as Principal Component Analysis (PCA)\nEvaluating clustering algorithms using metrics like silhouette score and inertia",
      "Module 5: Evaluation and Model Selection\n\nCross-validation techniques for estimating model performance\nOverfitting, underfitting, and regularization techniques\nHyperparameter tuning for optimizing model performance\nComparing and selecting the best-performing models",
      "Module 6: Neural Networks and Deep Learning\n\nUnderstanding the basics of artificial neural networks (ANN)\nActivation functions, backpropagation, and gradient descent\nBuilding and training deep learning models with TensorFlow or PyTorch\nConvolutional Neural Networks (CNN) for image recognition and processing",
      "Module 7: Natural Language Processing (NLP)\n\nBasics of text pre-processing and feature extraction\nBuilding text classification models using techniques like bag-of-words and TF-IDF\nSentiment analysis and text generation using recurrent neural networks (RNN)",
      "Module 8: Recommender Systems\n\nCollaborative filtering and content-based recommendation approaches\nImplementing recommendation algorithms such as matrix factorization and item-based filtering\nEvaluating recommendation systems using metrics like precision and recall",
      "Module 9: Deployment and Model Interpretability\n\nConverting machine learning models into production-ready formats\nDeploying models as web services or APIs\nModel interpretability techniques to understand and explain model predictions\nEthical considerations and bias in machine learning algorithms",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Data Science",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686910242/3156627_htzu9s.jpg",
    king: "https://aishala.in/img/courses/course_details_thumb_dive-in.gif",
    title: "Data Science Fundamentals",
    duration: "8-10 weeks",
    overview:
      "Dive into the world of data science and learn the essential skills to extract insights from data. Discover data cleaning, visualization, statistical analysis, and machine learning to solve real-world problems.",
    Training_program_benefits: [
      "Essential skills for extracting insights from data",
      "Data cleaning, visualization, and statistical analysis",
      "Introduction to machine learning for solving real-world problems",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Optional project for practical application",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Data Science\n\nUnderstanding the role and significance of data science in various industries\nExploring the data science lifecycle and the different stages involved\nOverview of data science tools, technologies, and job roles in the industry",
      "Module 2: Data Collection and Cleaning\n\nGathering and extracting data from various sources (APIs, databases, web scraping)\nHandling missing data, outliers, and data inconsistencies\nCleaning and transforming data for analysis and modeling",
      "Module 3: Exploratory Data Analysis (EDA)\n\nSummarizing and visualizing data using descriptive statistics and data visualization techniques\nIdentifying patterns, trends, and relationships in data\nConducting statistical analysis and hypothesis testing",
      "Module 4: Data Visualization\n\nCreating compelling visualizations to effectively communicate data insights\nChoosing appropriate charts, graphs, and visualization libraries\nEnhancing visualizations with interactivity and storytelling elements",
      "Module 5: Statistical Analysis\n\nApplying statistical techniques for data analysis and inference\nUnderstanding probability distributions, hypothesis testing, and statistical significance\nPerforming correlation analysis and regression modeling",
      "Module 6: Machine Learning\n\nIntroduction to supervised, unsupervised, and semi-supervised learning\nRegression, classification, and clustering algorithms\nModel evaluation, selection, and hyperparameter tuning\nHandling imbalanced datasets and performing feature selection",
      "Module 7: Big Data and Distributed Computing\n\nHandling large-scale datasets using distributed computing frameworks (e.g., Hadoop, Spark)\nExploring data processing and analysis with tools like MapReduce and Spark\nApplying machine learning algorithms to big data using scalable techniques",
      "Module 8: Natural Language Processing (NLP)\n\nProcessing and analyzing text data using NLP techniques\nText pre-processing, tokenization, and sentiment analysis\nBuilding text classification and language generation models",
      "Module 9: Data Science Ethics and Privacy\n\nUnderstanding ethical considerations and biases in data science\nPrivacy concerns, data anonymization, and security\nResponsible and fair use of data in the context of data science projects",
      "Module 10: Capstone Project\n\nApplying data science techniques and methodologies to solve a real-world problem\nDesigning and executing a data science project from end to end\nPresenting findings and insights through data visualizations and reports",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Linear Algebra",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Linear Algebra for Machine Learning",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "2-4 weeks",
    overview:
      "Develop a solid foundation in linear algebra, a fundamental mathematical framework for machine learning. Understand vectors, matrices, eigenvalues, and their applications in solving ML problems.",
    Training_program_benefits: [
      "Solid foundation in linear algebra for ML",
      "Understanding vectors, matrices, and eigenvalues",
      "Application of linear algebra in solving ML problems",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Linear Algebra\n\nUnderstanding vectors, matrices, and tensors\nBasic operations on vectors and matrices (addition, subtraction, multiplication)\nMatrix transposition, inverse, and determinant\nSolving systems of linear equations",
      "Module 2: Vector Spaces and Subspaces\n\nDefining vector spaces and subspaces\nLinear dependence and independence of vectors\nBasis and dimension of a vector space\nSpan and linear combinations",
      "Module 3: Matrix Operations and Transformations\n\nMatrix multiplication and properties\nMatrix rank and null space\nOrthogonal matrices and their applications\nEigenvalues and eigenvectors",
      "Module 4: Linear Transformations and Projections\n\nUnderstanding linear transformations and their geometric interpretation\nProjection matrices and their role in machine learning\nOrthogonal projections and least squares regression\nPrincipal Component Analysis (PCA) and dimensionality reduction",
      "Module 5: Matrix Decompositions\n\nLU decomposition and its applications\nQR decomposition for solving least squares problems\nSingular Value Decomposition (SVD) and its applications\nEigen decomposition and spectral theorem",
      "Module 6: Optimization and Gradient Descent\n\nIntroduction to optimization problems in machine learning\nGradient descent algorithm and its variants\nVector and matrix derivatives for optimization\nSolving constrained optimization problems",
      "Module 7: Applications of Linear Algebra in Machine Learning\n\nLinear regression and its relationship to linear algebra\nSupport Vector Machines (SVM) and kernel methods\nPrincipal Component Analysis (PCA) for dimensionality reduction\nRecommender systems and collaborative filtering",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Statistics",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Statistics Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Unlock the power of statistics for data analysis. Learn essential concepts like probability, hypothesis testing, regression analysis, and experimental design to make data-driven decisions.",
    Training_program_benefits: [
      "Unlocking the power of statistics for data analysis",
      "Concepts like probability, hypothesis testing, and regression analysis",
      "Experimental design for making data-driven decisions",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Statistics\n\nUnderstanding the importance of statistics in data analysis and decision-making\nDifferentiating between descriptive and inferential statistics\nExploring the basic statistical terminologies and concepts",
      "Module 2: Data Types and Measurement Scales\n\nIdentifying different types of data (categorical, numerical)\nUnderstanding measurement scales (nominal, ordinal, interval, ratio)\nHandling data transformation and normalization",
      "Module 3: Descriptive Statistics\n\nSummarizing and visualizing data using measures of central tendency (mean, median, mode)\nInterpreting variability and dispersion using measures of spread (variance, standard deviation)\nConstructing graphical representations (histograms, box plots, scatter plots)",
      "Module 4: Probability Theory\n\nUnderstanding the concept of probability and its applications\nComputation of probability using counting principles and probability rules\nCalculating conditional probability and independence\nExploring probability distributions (discrete and continuous)",
      "Module 5: Sampling and Sampling Distributions\n\nSampling techniques and their implications for statistical inference\nCentral Limit Theorem and its role in constructing sampling distributions\nEstimating population parameters using sample statistics\nConfidence intervals and margin of error",
      "Module 6: Hypothesis Testing\n\nFormulating null and alternative hypotheses\nConducting hypothesis tests using significance levels and p-values\nOne-sample, two-sample, and paired-sample tests\nInterpreting test results and making decisions based on hypothesis tests",
      "Module 7: Analysis of Variance (ANOVA)\n\nComparing means across multiple groups using ANOVA\nUnderstanding the F-statistic, p-value, and post-hoc tests\nANOVA assumptions and interpretation of results",
      "Module 8: Regression Analysis\n\nSimple linear regression for examining the relationship between two variables\nMultiple linear regression for modeling and prediction\nAssessing model fit, significance, and interpreting regression coefficients\nHandling assumptions and limitations of regression analysis",
      "Module 9: Nonparametric Methods\n\nNonparametric tests for situations with less stringent assumptions\nWilcoxon rank-sum test, Kruskal-Wallis test, and Spearman's rank correlation\nApplication of nonparametric methods in real-world scenarios",
      "Module 10: Experimental Design and Statistical Inference\n\nPrinciples of experimental design and randomized controlled trials\nAnalysis of variance for experimental data\nStatistical inference and causal inference\nEthical considerations in data collection and analysis",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Deep Learning",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Deep Learning Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Delve into the realm of deep learning, a cutting-edge field of AI. Discover neural networks, convolutional and recurrent networks, and train models to tackle complex tasks like image recognition and natural language processing.",
    Training_program_benefits: [
      "Exploration of cutting-edge deep learning techniques",
      "Understanding neural networks, convolutional and recurrent networks",
      "Training models for complex tasks like image recognition and NLP",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Deep Learning\n\nUnderstanding the basics of artificial neural networks and deep learning\nDifferentiating between shallow and deep networks\nExploring the history, motivations, and current trends in deep learning",
      "Module 2: Neural Network Architecture\n\nBuilding blocks of neural networks: neurons, activation functions, and layers\nFeedforward neural networks and backpropagation algorithm\nDeep architectures: convolutional neural networks (CNNs), recurrent neural networks (RNNs), and generative adversarial networks (GANs)",
      "Module 3: Training Deep Neural Networks\n\nData pre-processing and normalization techniques\nOptimizers and gradient descent variants\nRegularization methods: dropout, L1 and L2 regularization\nHandling overfitting and underfitting",
      "Module 4: Convolutional Neural Networks (CNNs)\n\nUnderstanding CNN architecture and its applications in computer vision\nConvolutional layers, pooling layers, and activation functions\nTransfer learning and pre-trained CNN models\nObject detection, image classification, and image segmentation with CNNs",
      "Module 5: Recurrent Neural Networks (RNNs)\n\nSequential data and its challenges in deep learning\nRNN architecture and working principles\nLong Short-Term Memory (LSTM) and Gated Recurrent Units (GRU)\nApplications of RNNs: natural language processing, speech recognition, and time series prediction",
      "Module 6: Generative Adversarial Networks (GANs)\n\nUnderstanding the concept of GANs and its architecture\nGenerator and discriminator networks in GANs\nTraining GANs and overcoming challenges\nGenerating realistic images, text, and music with GANs",
      "Module 7: Deep Reinforcement Learning\n\nReinforcement learning basics and its connection to deep learning\nQ-Learning, Deep Q-Networks (DQN), and policy gradients\nApplications of deep reinforcement learning in game playing and robotics",
      "Module 8: Natural Language Processing (NLP) with Deep Learning\n\nWord embeddings and distributed representations\nRecurrent Neural Networks (RNNs) for language modeling and text generation\nSequence-to-Sequence models and attention mechanisms\nSentiment analysis and machine translation using deep learning",
      "Module 9: Deployment and Model Optimization\n\nConverting deep learning models for deployment on different platforms\nModel optimization techniques for inference speed and memory efficiency\nDeployment considerations and best practices for real-world applications\nEthical considerations and fairness in deep learning algorithms",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Big Data",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Big Data, Hadoop, and Spark Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Harness the potential of big data technologies. Learn to process large datasets using Hadoop and utilize the power of Apache Spark for distributed data processing and analytics.",
    Training_program_benefits: [
      "Harnessing the potential of big data technologies",
      "Processing large datasets using Hadoop",
      "Utilizing Apache Spark for distributed data processing and analytics",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Big Data\n\nUnderstanding the characteristics and challenges of big data\nExploring the three V's of big data: volume, velocity, and variety\nIdentifying the applications and impact of big data across industries",
      "Module 2: Hadoop Fundamentals\n\nOverview of the Hadoop ecosystem and its components (HDFS, YARN, MapReduce)\nSetting up a Hadoop cluster and managing distributed storage\nWriting and executing MapReduce jobs for data processing",
      "Module 3: Data Ingestion and Storage\n\nTechniques for data ingestion from various sources (batch and real-time)\nDistributed file systems and data storage formats (e.g., Avro, Parquet)\nData partitioning and replication for fault tolerance and scalability",
      "Module 4: Hadoop Data Processing\n\nUnderstanding the MapReduce programming model for distributed computing\nWriting MapReduce programs in Java or using higher-level frameworks (e.g., Apache Pig, Apache Hive)\nPerforming data transformations, aggregations, and joins",
      "Module 5: Hadoop Ecosystem Tools\n\nExploring additional tools in the Hadoop ecosystem (e.g., Apache Sqoop, Apache Flume, Apache Kafka)\nExtracting data from relational databases and streaming sources\nData integration and data pipeline management",
      "Module 6: Introduction to Apache Spark\n\nUnderstanding the advantages of Apache Spark over traditional MapReduce\nWorking with resilient distributed datasets (RDDs)\nSpark's core components: Spark SQL, Spark Streaming, Spark MLlib, and GraphX",
      "Module 7: Spark Data Processing\n\nTransforming and analyzing large-scale data using Spark's Data Frame and Dataset APIs\nApplying SQL queries, aggregations, and joins with Spark SQL\nStream processing and real-time analytics with Spark Streaming",
      "Module 8: Machine Learning with Spark\n\nIntroduction to Spark MLlib for scalable machine learning\nBuilding and evaluating machine learning models using Spark\nHandling large-scale datasets and performing feature engineering",
      "Module 9: Spark Graph Processing\n\nProcessing and analyzing graph data with GraphX\nGraph algorithms and graph analytics with Spark\nSocial network analysis and recommendation systems",
      "Module 10: Data Visualization and Reporting\n\nVisualizing and communicating insights from big data\nExploring data visualization tools (e.g., Apache Zeppelin, Tableau)\nCreating interactive dashboards and reports",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "PySpark",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "PySpark and Spark ML Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Master PySpark, the Python API for Apache Spark. Explore data manipulation, feature engineering, and machine learning with Spark MLlib to build scalable and efficient data pipelines.",
    Training_program_benefits: [
      "Mastering PySpark, the Python API for Spark",
      "Data manipulation, feature engineering, and ML with Spark MLlib",
      "Building scalable and efficient data pipelines",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],

    Curriculum: [
      "Module 1: Introduction to Apache Spark and PySpark\n\nUnderstanding the advantages of Apache Spark and its architecture\nOverview of PySpark and its integration with Python\nSetting up a PySpark environment and working with RDDs (Resilient Distributed Datasets)",
      "Module 2: Data Manipulation and Transformation with PySpark\n\nPerforming data ingestion from various sources (e.g., CSV, JSON, Parquet)\nData cleaning, filtering, and transforming operations using PySpark\nWorking with structured and semi-structured data",
      "Module 3: PySpark SQL and Data Frames\n\nIntroduction to PySpark SQL and its role in data analysis\nQuerying and manipulating data using SQL-like syntax with Data Frames\nApplying aggregations, joins, and filtering operations",
      "Module 4: PySpark Streaming\n\nReal-time data processing and stream processing with PySpark\nWorking with streaming data sources (e.g., Kafka, Flume)\nWindowing operations and stateful stream processing",
      "Module 5: Introduction to Spark MLlib\n\nUnderstanding the machine learning capabilities of Spark MLlib\nOverview of the MLlib pipeline API and its components\nFeature extraction, transformation, and selection techniques",
      "Module 6: Supervised Learning with Spark ML\n\nClassification algorithms: Logistic Regression, Decision Trees, Random Forests, Gradient-Boosted Trees\nRegression algorithms: Linear Regression, Decision Trees Regression\nModel evaluation and hyperparameter tuning with cross-validation",
      "Module 7: Unsupervised Learning with Spark ML\n\nClustering algorithms: K-means, Gaussian Mixture Models\nDimensionality reduction techniques: Principal Component Analysis (PCA)\nAnomaly detection and outlier detection",
      "Module 8: Collaborative Filtering and Recommendation Systems\n\nBuilding recommendation systems using Spark MLlib\nMatrix factorization techniques: Alternating Least Squares (ALS)\nHandling large-scale datasets for collaborative filtering",
      "Module 9: Spark ML Pipelines and Model Deployment\n\nUnderstanding Spark ML Pipelines for end-to-end machine learning workflows\nSaving and loading ML models for production deployment\nModel serialization and deployment considerations",
      "Module 10: Advanced Topics and Integration\n\nFeature engineering techniques for advanced data pre-processing\nIntegration with external libraries and tools (e.g., TensorFlow, XGBoost)\nWorking with big data frameworks (e.g., Hadoop, Hive) in conjunction with PySpark",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "C and C++",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "C and C++ Programming Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "8-10 weeks",
    overview:
      "Learn the foundational languages of C and C++. Gain expertise in programming concepts, memory management, and build essential skills for system-level development and performance-critical applications",
    Training_program_benefits: [
      "Learning foundational languages of C and C++",
      "Expertise in programming concepts and memory management",
      "Essential skills for system-level development and performance-critical applications",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Programming\n\nUnderstanding the basics of programming concepts and algorithms\nOverview of the software development life cycle\nSetting up a development environment for C and C++ programming",
      "Module 2: Introduction to C Programming\n\nOverview of the C programming language and its features\nVariables, data types, and basic input/output operations\nControl flow structures: loops, conditionals, and branching\nFunctions and modular programming in C",
      "Module 3: C Language Fundamentals\n\nArrays, strings, and pointers in C\nMemory management and dynamic memory allocation\nFile handling and input/output operations in C\nError handling and debugging techniques",
      "Module 4: Object-Oriented Programming with C++\n\nIntroduction to object-oriented programming (OOP) concepts\nClasses, objects, and encapsulation in C++\nInheritance, polymorphism, and abstraction in C++\nOperator overloading and function templates",
      "Module 5: C++ Language Features\n\nAdvanced data structures: vectors, lists, and maps in C++\nException handling and error propagation in C++\nStandard Template Library (STL) and its components\nMultithreading and concurrent programming in C++",
      "Module 6: Memory Management and Optimization\n\nUnderstanding memory management in C and C++\nPointers, references, and memory allocation techniques\nMemory leaks and memory corruption issues\nPerformance optimization techniques for C and C++ programs",
      "Module 7: Advanced Topics and Libraries\n\nAdvanced I/O operations and file handling in C and C++\nNetworking and socket programming using C and C++\nInterfacing with hardware and low-level programming\nIntroduction to popular C and C++ libraries (e.g., Boost, Qt)",
      "Module 8: Debugging and Testing\n\nDebugging techniques and tools for C and C++ programs\nUnit testing and test-driven development (TDD) in C and C++\nCode profiling and performance analysis",
      "Module 9: Best Practices and Coding Standards\n\nWriting clean and maintainable code in C and C++\nCoding standards and style guidelines\nDocumentation and code commenting practices\nCode reviews and version control integration",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Java Programming",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Java and Advanced Java Programming",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "8-10 weeks",
    overview:
      "Master Java, the versatile programming language used in a wide range of applications. Explore advanced topics like multithreading, networking, and database connectivity to build robust Java applications.",
    Training_program_benefits: [
      "Mastering the versatile programming language of Java",
      "Advanced topics like multithreading, networking, and database connectivity",
      "Building robust Java applications",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Java\n\nUnderstanding the Java platform and its advantages\nSetting up a Java development environment\nWriting and running your first Java program\nIntroduction to Java syntax, data types, and variables",
      "Module 2: Object-Oriented Programming with Java\n\nUnderstanding the principles of object-oriented programming (OOP)\nClasses, objects, and encapsulation in Java\nInheritance, polymorphism, and abstraction in Java\nInterfaces and abstract classes in Java",
      "Module 3: Java Language Fundamentals\n\nControl flow structures: loops, conditionals, and branching\nException handling and error propagation in Java\nWorking with arrays, collections, and generics in Java\nInput/output operations with Java streams",
      "Module 4: Java Core Libraries\n\nExploring the Java Standard Library and its key packages\nWorking with dates, times, and formatting in Java\nFile handling and input/output operations in Java\nJava networking fundamentals: sockets and protocols",
      "Module 5: Multithreading and Concurrency\n\nIntroduction to multithreading and concurrent programming in Java\nThread creation, synchronization, and inter-thread communication\nJava thread pools and executor framework\nManaging concurrent access to shared resources",
      "Module 6: Java Database Connectivity (JDBC)\n\nIntroduction to database concepts and relational databases\nEstablishing database connections and executing SQL queries with JDBC\nWorking with result sets and performing database updates\nHandling transactions and managing database resources",
      "Module 7: Java Servlets and JavaServer Pages (JSP)\n\nIntroduction to web development with Java Servlets and JSP\nHandling HTTP requests and building dynamic web applications\nSession management and servlet filters\nJavaServer Pages Standard Tag Library (JSTL) and expression language",
      "Module 8: Java Enterprise Edition (Java EE) Overview\n\nOverview of Java EE architecture and components\nIntroduction to Enterprise JavaBeans (EJB) and Java Persistence API (JPA)\nJavaServer Faces (JSF) for building web interfaces\nJava Message Service (JMS) and messaging concepts",
      "Module 9: Java Frameworks and Libraries\n\nIntroduction to popular Java frameworks (e.g., Spring, Hibernate)\nDependency management with Apache Maven\nIntroduction to RESTful web services with Java\nIntroduction to testing frameworks (e.g., JUnit, Mockito)",
      "Module 10: Advanced Java Topics\n\nJava reflection and dynamic class loading\nSecurity considerations in Java applications\nIntroduction to JavaFX for building desktop applications\nJava performance optimization and memory management techniques",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Flutter",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Mobile App Development with Flutter",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Build cross-platform mobile apps using Flutter framework. Learn Dart programming language, UI development, state management, and integration with backend services to create stunning mobile applications.",
    Training_program_benefits: [
      "Building cross-platform mobile apps using Flutter",
      "Learning Dart programming language",
      "UI development and state management",
      "Integration with backend services",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Opportunity for internship with AI-Shala",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Mobile App Development and Flutter\n\nOverview of mobile app development and Flutter framework\nSetting up a Flutter development environment\nIntroduction to Dart programming language and its syntax\nBuilding and running your first Flutter app",
      "Module 2: Flutter Widgets and UI Design\n\nUnderstanding Flutter widgets and widget hierarchy\nBuilding responsive and adaptive UI layouts with Flutter\nWorking with various widgets: containers, buttons, text fields, etc.\nHandling user input and gestures",
      "Module 3: State Management in Flutter\n\nUnderstanding the concept of state and managing state in Flutter\nExploring different state management approaches (e.g., setState, Provider, BLoC)\nImplementing reactive UI updates with Flutter's reactive framework",
      "Module 4: Navigation and Routing in Flutter\n\nNavigating between screens and managing app routes in Flutter\nImplementing navigation drawers, bottom navigation bars, and tabs\nPassing data between screens using route parameters",
      "Module 5: Flutter Widgets for App Logic and Functionality\n\nUsing Flutter widgets for form validation and user input handling\nWorking with lists and grids to display dynamic content\nAnimation and motion in Flutter apps\nIntegrating device features (e.g., camera, GPS) using Flutter plugins",
      "Module 6: Networking and API Integration\n\nMaking HTTP requests and handling responses in Flutter\nConsuming RESTful APIs and working with JSON data\nAuthentication and authorization in Flutter apps\nCaching and offline data storage",
      "Module 7: Firebase Integration for Flutter Apps\n\nIntroduction to Firebase backend services for mobile apps\nSetting up Firebase project and integrating Firebase SDK with Flutter\nUser authentication with Firebase Authentication\nReal-time database and cloud storage with Firebase Firestore",
      "Module 8: Stateful Data Management in Flutter\n\nImplementing advanced state management techniques in Flutter\nUsing Provider package for efficient and scalable state management\nRedux pattern and managing app state with Redux in Flutter",
      "Module 9: Testing and Debugging Flutter Apps\n\nTesting Flutter widgets and app logic using Flutter testing framework\nDebugging techniques and tools for Flutter apps\nPerformance profiling and optimization of Flutter apps\nError handling and logging best practices",
      "Module 10: Deployment and Publishing\n\nGenerating release builds for iOS and Android platforms\nApp signing and publishing to app stores (Google Play Store, Apple App Store)\nContinuous integration and delivery (CI/CD) for Flutter apps\nApp store optimization (ASO) and marketing strategies",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "DSA",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Data Structures and Algorithms",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "8-10 weeks",
    overview:
      "Develop a strong grasp of data structures and algorithms. Solve coding problems efficiently, implement common data structures, and optimize algorithms for better performance.",
    Training_program_benefits: [
      "Strong grasp of data structures and algorithms",
      "Efficient problem-solving and coding skills",
      "Implementation of common data structures",
      "Algorithm optimization for better performance",
      "Live lectures with coding",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Data Structures and Algorithms\n\nOverview of data structures and algorithms\nImportance and applications in software development",
      "Module 2: Arrays and Strings\n\nArray manipulation and operations\nString manipulation and algorithms",
      "Module 3: Linked Lists\n\nSingly linked lists\nDoubly linked lists\nCircular linked lists\nLinked list operations and algorithms",
      "Module 4: Stacks and Queues\n\nStack implementation and operations\nQueue implementation and operations\nApplications of stacks and queues",
      "Module 5: Trees and Binary Trees\n\nBinary tree representation and traversal\nBinary search tree and its operations\nTree traversal algorithms (inorder, preorder, postorder)",
      "Module 6: Heaps and Priority Queues\n\nMin and max heaps\nHeap operations and algorithms\nPriority queues and their applications",
      "Module 7: Hash Tables\n\nHashing techniques and collision resolution\nHash table implementation and operations\nHash table applications and analysis",
      "Module 8: Graphs and Graph Algorithms\n\nGraph representation (adjacency matrix, adjacency list)\nGraph traversal algorithms (BFS, DFS)\nShortest path algorithms (Dijkstra's, Bellman-Ford)",
      "Module 9: Sorting Algorithms\n\nComparison-based sorting algorithms (selection sort, insertion sort, bubble sort)\nEfficient sorting algorithms (merge sort, quicksort, heapsort)\nTime and space complexity analysis of sorting algorithms",
      "Module 10: Searching Algorithms\n\nLinear search\nBinary search\nHash-based searching",
      "Module 11: Algorithm Design Techniques\n\nDivide and conquer\nGreedy algorithms\nDynamic programming\nBacktracking",
      "Module 12: Algorithm Analysis and Complexity\n\nBig O notation and time complexity analysis\nSpace complexity analysis\nBest, worst, and average case analysis",
      "Module 13: Advanced Topics (Optional)\n\nAdvanced data structures (AVL trees, B-trees, etc.)\nAdvanced algorithms (graph algorithms, string matching, etc.)",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Linux Administration",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Linux Administration",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Become proficient in Linux system administration. Learn essential commands, manage users and permissions, automate tasks with scripting, and troubleshoot common issues in a Linux environment.",
    Training_program_benefits: [
      "Proficiency in Linux system administration",
      "Essential commands and tasks automation with scripting",
      "User management, permissions, and troubleshooting",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Linux Operating System\n\nOverview of Linux distributions\nUnderstanding Linux architecture\nBasic Linux commands and file system navigation",
      "Module 2: User and Group Management\n\nCreating and managing user accounts\nConfiguring user privileges and permissions\nGroup management and permissions",
      "Module 3: File System Management\n\nWorking with file permissions and ownership\nManaging files and directories\nDisk partitioning and file system types",
      "Module 4: Process Management\n\nMonitoring and controlling processes\nManaging process priorities and signals\nProcess scheduling and resource utilization",
      "Module 5: System Services and Startup Processes\n\nUnderstanding system services and daemons\nManaging services using systemd\nConfiguring startup processes and runlevels",
      "Module 6: Network Configuration and Services\n\nConfiguring network interfaces\nSetting up IP addressing and routing\nManaging network services (DNS, DHCP, SSH)",
      "Module 7: System Backup and Recovery\n\nBackup strategies and tools\nRestoring files and directories\nSystem recovery procedures",
      "Module 8: System Security and Authentication\n\nUser authentication mechanisms (passwords, SSH keys)\nSecuring user accounts and access\nFirewall configuration and network security",
      "Module 9: Package Management\n\nManaging software packages using package managers (apt, yum)\nDependency resolution and package repositories\nPackage installation, upgrade, and removal",
      "Module 10: System Monitoring and Performance Optimization\n\nMonitoring system resources (CPU, memory, disk)\nPerformance tuning and optimization\nTroubleshooting common performance issues",
      "Module 11: Shell Scripting Basics\n\nIntroduction to shell scripting (Bash)\nWriting and executing shell scripts\nAutomating tasks with scripts",
      "Module 12: Linux Server Deployment (Optional)\n\nConfiguring Linux servers for specific purposes (web server, database server, etc.)\nWeb hosting setup and configuration",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Operating Systems",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Fundamentals of Operating Systems",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Gain a comprehensive understanding of operating systems. Explore process management, memory allocation, file systems, and security concepts to comprehend the core principles of modern operating systems.",
    Training_program_benefits: [
      "Comprehensive understanding of operating systems",
      "Process management, memory allocation, and file systems",
      "Security concepts and principles",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],

    Curriculum: [
      "Module 1: Introduction to Operating Systems\n\nDefinition and purpose of an operating system\nEvolution and types of operating systems\nOverview of key operating system components",
      "Module 2: Process Management\n\nProcess concepts and characteristics\nProcess states and scheduling algorithms\nInterprocess communication and synchronization",
      "Module 3: Memory Management\n\nMemory hierarchy and virtual memory\nMemory allocation techniques\nPaging and segmentation",
      "Module 4: File Systems and I/O Management\n\nFile system organization and structure\nFile operations and access methods\nDisk scheduling and I/O management",
      "Module 5: Device Management\n\nDevice drivers and device management\nI/O control and interrupt handling\nDevice allocation and resource sharing",
      "Module 6: CPU Scheduling\n\nScheduling algorithms and policies\nProcess scheduling metrics and evaluation\nMultilevel queue and priority scheduling",
      "Module 7: Deadlocks\n\nDeadlock prevention, avoidance, and detection\nResource allocation and deadlock recovery",
      "Module 8: Security and Protection\n\nSecurity threats and mechanisms\nAccess control and authentication\nUser authentication and file permissions",
      "Module 9: Distributed Systems\n\nDistributed system concepts and architectures\nCommunication models and protocols\nDistributed file systems and synchronization",
      "Module 10: Operating System Design and Implementation\n\nOperating system structure and components\nKernel architecture and system calls\nOperating system boot process",
      "Module 11: Case Studies (Optional)\n\nAnalysis of real-world operating systems (e.g., Windows, Linux, macOS)\nComparison of different operating system designs and features",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Data Analysis and Visualization",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Python Libraries for Data Analysis and Visualization",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Master essential Python libraries for data analysis and visualization. Utilize Pandas and NumPy for data manipulation, and create stunning visualizations with Plotly, Bokeh, and Matplotlib.",
    Training_program_benefits: [
      "Mastering essential Python libraries for data analysis and visualization",
      "Data manipulation with Pandas and NumPy",
      "Creating stunning visualizations with Plotly, Bokeh, and Matplotlib",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Data Analysis and Visualization in Python\n\nOverview of Python as a data analysis and visualization tool\nImportance and applications of data analysis and visualization",
      "Module 2: Introduction to Pandas\n\nData structures in Pandas (Series, DataFrame)\nLoading and manipulating data with Pandas\nData cleaning and preprocessing using Pandas",
      "Module 3: NumPy for Numerical Computing\n\nIntroduction to NumPy arrays and multidimensional arrays\nMathematical computations and array manipulation using NumPy\nLinear algebra operations with NumPy",
      "Module 4: Data Visualization with Matplotlib\n\nBasic plotting concepts and techniques\nLine plots, scatter plots, bar plots, and histograms\nCustomizing plots, adding annotations, and applying styles",
      "Module 5: Interactive Visualizations with Plotly\n\nCreating interactive charts, graphs, and maps with Plotly\nCustomizing interactive elements and tooltips\nCreating dashboards and web-based visualizations",
      "Module 6: Interactive Web-based Visualizations with Bokeh\n\nIntroduction to Bokeh and its key features\nBuilding interactive visualizations with Bokeh\nAdding interactivity, widgets, and interactions to plots",
      "Module 7: Advanced Data Visualization Techniques\n\nGeospatial data visualization with GeoPandas and Folium\nNetwork visualization with NetworkX\nTime series visualization and plotting",
      "Module 8: Data Analysis and Visualization Case Studies\n\nPractical examples and case studies applying the learned libraries\nExploratory data analysis and visualization workflows",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Computer Vision",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Computer Vision Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Enter the exciting world of computer vision. Learn image processing techniques, feature extraction, and deep learning algorithms to analyze and understand visual data.",
    Training_program_benefits: [
      "Entering the exciting world of computer vision",
      "Image processing techniques and feature extraction",
      "Deep learning algorithms for visual data analysis",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Computer Vision\n\nOverview of computer vision and its applications\nHistorical developments and current trends\nChallenges and limitations in computer vision",
      "Module 2: Image Processing Techniques\n\nImage representation and manipulation\nImage enhancement and filtering\nImage transformations and geometric operations",
      "Module 3: Image Feature Extraction\n\nIntroduction to image features and descriptors\nFeature extraction techniques (e.g., edge detection, corner detection)\nFeature matching and point correspondences",
      "Module 4: Object Detection and Tracking\n\nObject detection algorithms (e.g., Haar cascades, HOG, R-CNN)\nObject tracking techniques (e.g., Kalman filter, optical flow)\nMultiple object detection and tracking",
      "Module 5: Image Classification and Recognition\n\nIntroduction to image classification and recognition\nFeature-based classification algorithms (e.g., SVM, K-NN)\nDeep learning-based classification (e.g., Convolutional Neural Networks)",
      "Module 6: Camera Calibration and 3D Vision\n\nCamera models and calibration techniques\nStereo vision and depth estimation\n3D reconstruction from multiple images",
      "Module 7: Motion Analysis and Video Processing\n\nMotion detection and estimation\nVideo stabilization and object tracking in videos\nVideo summarization and activity recognition",
      "Module 8: Deep Learning for Computer Vision\n\nOverview of deep learning architectures for computer vision (e.g., CNNs)\nTransfer learning and pre-trained models\nObject detection and image segmentation with deep learning",
      "Module 9: Applications of Computer Vision\n\nFace detection and recognition\nObject recognition and image retrieval\nAugmented reality and virtual reality",
      "Module 10: Case Studies and Projects\n\nPractical implementation of computer vision algorithms\nHands-on projects applying computer vision techniques to real-world problems",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Natural Language Processing",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Natural Language Processing Fundamentals",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Dive into natural language processing and understand human language with the help of computers. Explore text preprocessing, sentiment analysis, and language modeling to build powerful NLP applications.",
    Training_program_benefits: [
      "Diving into natural language processing",
      "Text preprocessing and sentiment analysis",
      "Language modeling and text generation",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Natural Language Processing\n\nOverview of NLP and its applications\nChallenges and complexities in processing human language\nNLP pipeline and key components",
      "Module 2: Text Preprocessing\n\nTokenization and text segmentation\nStop word removal and stemming\nPart-of-speech tagging and syntactic parsing",
      "Module 3: Language Modeling and Text Representation\n\nN-gram models and language modeling\nVector space models and word embeddings\nWord2Vec and GloVe models",
      "Module 4: Sentiment Analysis\n\nIntroduction to sentiment analysis\nSentiment classification techniques (e.g., Naive Bayes, SVM, neural networks)\nAspect-based sentiment analysis",
      "Module 5: Named Entity Recognition\n\nNamed entity recognition (NER) task\nNER approaches and algorithms\nEntity linking and disambiguation",
      "Module 6: Text Classification and Topic Modeling\n\nText classification algorithms (e.g., Naive Bayes, SVM, neural networks)\nTopic modeling techniques (e.g., LDA, LSA)\nDocument clustering and classification",
      "Module 7: Text Summarization and Generation\n\nExtractive and abstractive text summarization\nText generation techniques (e.g., Markov chains, recurrent neural networks)\nSummarization evaluation metrics",
      "Module 8: Machine Translation and Language Generation\n\nMachine translation models and techniques\nNeural machine translation and sequence-to-sequence models\nLanguage generation and dialogue systems",
      "Module 9: Advanced NLP Techniques\n\nNamed entity disambiguation and resolution\nDependency parsing and syntactic analysis\nCoreference resolution and co-reference chains",
      "Module 10: NLP Applications and Future Trends\n\nQuestion answering systems\nSentiment analysis in social media\nMultilingual and cross-lingual NLP",
      "Module 11: Case Studies and Projects\n\nPractical implementation of NLP techniques and algorithms\nHands-on projects applying NLP to real-world text data",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Image Processing",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Image Processing and Computer Vision",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Discover the techniques to process and analyze digital images. Gain insights into image enhancement, object recognition, and pattern recognition using computer vision algorithms.",
    Training_program_benefits: [
      "Techniques for processing and analyzing digital images",
      "Image enhancement, object recognition, and pattern recognition",
      "Computer vision algorithms for visual data interpretation",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Image Processing and Computer Vision\n\nOverview of image processing and computer vision\nImage representation and digital image fundamentals\nApplications and significance of image processing and computer vision",
      "Module 2: Image Enhancement and Restoration\n\nHistogram equalization and contrast enhancement\nNoise reduction techniques (e.g., Gaussian, median filtering)\nImage denoising and restoration algorithms",
      "Module 3: Image Filtering and Edge Detection\n\nConvolution and filtering operations\nLinear and nonlinear filters (e.g., Gaussian, Sobel)\nEdge detection techniques (e.g., Canny edge detection)",
      "Module 4: Image Segmentation\n\nThresholding and region-based segmentation\nEdge-based segmentation and contour detection\nClustering algorithms for image segmentation",
      "Module 5: Feature Extraction and Representation\n\nLocal feature descriptors (e.g., SIFT, SURF)\nScale-invariant feature transform (SIFT)\nFeature matching and image registration",
      "Module 6: Object Detection and Recognition\n\nHaar cascades and object detection techniques\nFeature-based object recognition algorithms\nDeep learning-based object detection (e.g., Faster R-CNN, YOLO)",
      "Module 7: Motion Analysis and Tracking\n\nOptical flow and motion estimation\nObject tracking algorithms (e.g., Kalman filter, MeanShift)\nMultiple object tracking and trajectory analysis",
      "Module 8: 3D Vision and Stereo Imaging\n\nDepth perception and stereo imaging principles\nStereo correspondence and disparity estimation\n3D reconstruction from multiple images",
      "Module 9: Deep Learning for Computer Vision\n\nConvolutional Neural Networks (CNNs) for image classification\nTransfer learning and pre-trained CNN models\nDeep learning-based image segmentation and object detection",
      "Module 10: Image and Video Understanding\n\nImage understanding and scene understanding\nVideo analysis and activity recognition\nVideo-based surveillance systems",
      "Module 11: Case Studies and Projects\n\nPractical implementation of image processing and computer vision algorithms\nHands-on projects applying computer vision techniques to real-world scenarios",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Internet of Things",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Time Series and IoT Data Analytics",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Learn the art of analyzing time series and IoT data. Explore methods for forecasting, anomaly detection, and extracting valuable insights from time-dependent data in various IoT applications.",
    Training_program_benefits: [
      "Art of analyzing time series and IoT data",
      "Forecasting, anomaly detection, and insights extraction",
      "Applications in various IoT domains",
      "Live lectures with coding exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to Time Series Data and IoT Analytics\n\nOverview of time series data and its characteristics\nIntroduction to IoT data and its challenges\nApplications and importance of time series and IoT analytics",
      "Module 2: Time Series Visualization and Exploratory Data Analysis\n\nPlotting time series data and trends\nSeasonality and periodicity analysis\nData decomposition and trend identification",
      "Module 3: Time Series Forecasting\n\nForecasting techniques (e.g., ARIMA, exponential smoothing)\nLong Short-Term Memory (LSTM) for time series forecasting\nEvaluating forecast accuracy and performance",
      "Module 4: Time Series Anomaly Detection\n\nStatistical methods for anomaly detection (e.g., Z-score, Mahalanobis distance)\nMachine learning-based anomaly detection algorithms\nHandling anomalies in time series data",
      "Module 5: IoT Data Integration and Preprocessing\n\nHandling and preprocessing IoT sensor data\nData alignment and synchronization\nDealing with missing values and outliers",
      "Module 6: Feature Extraction and Selection for IoT Data\n\nExtracting meaningful features from IoT data\nDimensionality reduction techniques\nFeature selection methods for IoT analytics",
      "Module 7: Predictive Analytics for IoT Data\n\nBuilding predictive models for IoT data\nRegression and classification algorithms for IoT analytics\nModel evaluation and performance metrics",
      "Module 8: Real-Time Analytics for IoT Data Streams\n\nStream processing techniques for real-time analytics\nHandling high-velocity IoT data streams\nReal-time anomaly detection and prediction",
      "Module 9: IoT Data Visualization and Dashboards\n\nCreating interactive visualizations for IoT data\nDesigning dashboards for real-time monitoring\nCommunicating insights effectively through visualizations",
      "Module 10: Case Studies and Projects\n\nPractical implementation of time series and IoT analytics\nHands-on projects applying analytics techniques to IoT datasets",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Github",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Industrialization with GitHub and CI/CD Pipelines",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "2-4 weeks",
    overview:
      "Learn industry best practices for software development. Utilize Git for version control, set up CI/CD pipelines for automated testing and deployment, and streamline the development process.",
    Training_program_benefits: [
      "Industry best practices for software development",
      "Version control with Git",
      "CI/CD pipelines for automated testing and deployment",
      "Streamlining the development process",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to GitHub\n\nOverview of version control systems and Git\nSetting up a GitHub repository and configuring access controls\nBranching, merging, and resolving conflicts in Git",
      "Module 2: Collaborative Development with GitHub\n\nCollaborating with team members using GitHub\nPull requests and code reviews\nGitHub workflows and issue tracking",
      "Module 3: Introduction to CI/CD Pipelines\n\nUnderstanding the CI/CD pipeline concept\nBenefits of automated software delivery\nCI/CD tools and platforms",
      "Module 4: Building and Testing Automation\n\nSetting up build automation with build tools (e.g., Maven, Gradle)\nUnit testing and test automation frameworks\nIntegrating code quality checks and static analysis tools",
      "Module 5: Continuous Integration (CI) with GitHub Actions\n\nIntroduction to GitHub Actions for CI\nDefining workflows for build and test automation\nTriggering workflows on code changes and pull requests",
      "Module 6: Continuous Deployment (CD) with CI/CD Pipelines\n\nIntroduction to CD and deployment strategies\nAutomating deployment with CI/CD pipelines\nIntegration with deployment platforms (e.g., AWS, Azure, Docker)",
      "Module 7: Infrastructure as Code (IaC) and Configuration Management\n\nInfrastructure as Code principles and tools (e.g., Terraform)\nConfiguration management tools (e.g., Ansible)\nProvisioning and managing development and production environments",
      "Module 8: Monitoring and Error Tracking\n\nImplementing monitoring and logging solutions\nError tracking and alerting mechanisms\nUsing monitoring data to optimize the CI/CD pipeline",
      "Module 9: Security and Compliance in CI/CD\n\nIncorporating security practices in the CI/CD pipeline\nVulnerability scanning and code analysis\nCompliance considerations and best practices",
      "Module 10: CI/CD Pipeline Orchestration and Optimization\n\nPipeline orchestration tools (e.g., Jenkins, GitLab CI/CD)\nOptimizing the CI/CD pipeline for speed and efficiency\nImplementing parallelization and caching strategies",
      "Module 11: Case Studies and Projects\n\nHands-on projects implementing GitHub workflows and CI/CD pipelines\nReal-world case studies showcasing industrial software development practices",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "Database Management Systems",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "Database Management Systems (DBMS) with Oracle and MySQL",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "6-8 weeks",
    overview:
      "Master the fundamentals of database management systems. Learn SQL programming, data modeling, and gain hands-on experience with Oracle and MySQL databases.",
    Training_program_benefits: [
      "Fundamentals of database management systems",
      "SQL programming and data modeling",
      "Hands-on experience with Oracle and MySQL databases",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to DBMS and Relational Databases\n\nOverview of database management systems\nRelational model and relational database concepts\nDatabase design principles and normalization",
      "Module 2: SQL Programming and Data Manipulation\n\nStructured Query Language (SQL) fundamentals\nQuerying and retrieving data from databases\nData manipulation and update operations",
      "Module 3: Data Modeling and Entity-Relationship Diagrams\n\nConceptual data modeling using Entity-Relationship (ER) diagrams\nMapping ER diagrams to relational schemas\nNormalization and denormalization techniques",
      "Module 4: Advanced SQL Queries and Joins\n\nComplex SQL queries and subqueries\nAggregate functions and grouping data\nInner and outer joins for data retrieval",
      "Module 5: Database Indexing and Query Optimization\n\nIndexing concepts and types\nQuery optimization techniques\nPerformance tuning and execution plans",
      "Module 6: Transaction Management and Concurrency Control\n\nACID properties of database transactions\nConcurrency control and locking mechanisms\nIsolation levels and transaction management strategies",
      "Module 7: Database Administration and Security\n\nDatabase administration tasks and responsibilities\nUser and access management\nBackup and recovery techniques",
      "Module 8: Oracle Database Management\n\nIntroduction to Oracle Database\nOracle data types and objects\nOracle SQL and PL/SQL programming",
      "Module 9: MySQL Database Management\n\nIntroduction to MySQL Database\nMySQL data types and storage engines\nMySQL SQL and stored procedures",
      "Module 10: Database Connectivity and Application Development\n\nConnecting databases with programming languages (e.g., Python, Java)\nDatabase APIs and drivers\nDeveloping database-driven applications",
      "Module 11: Case Studies and Projects\n\nHands-on projects and exercises using Oracle and MySQL databases\nReal-world case studies demonstrating practical database management scenarios",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
  {
    domain: "MongoDB and Firebase",
    king: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832214/Machine_Learning__ML__2_tsfojp.jpg",
    title: "MongoDB and Firebase for Modern Data Management",
    img: "https://res.cloudinary.com/dd6g64flm/image/upload/v1686832213/Machine_Learning__ML__1_sg6p10.jpg",
    duration: "4-6 weeks",
    overview:
      "Explore modern NoSQL databases like MongoDB and Firebase. Learn to model data, perform CRUD operations, and integrate these databases into your applications for scalability and real-time capabilities.",
    Training_program_benefits: [
      "Exploring modern NoSQL databases like MongoDB and Firebase",
      "Data modeling and CRUD operations",
      "Integration into applications for scalability and real-time capabilities",
      "Live lectures with hands-on exercises",
      "Quizzes for self-assessment",
      "Certificate program",
    ],
    Curriculum: [
      "Module 1: Introduction to NoSQL Databases and MongoDB\n\nOverview of NoSQL databases and their advantages\nIntroduction to MongoDB and its features\nDocument-oriented data model and BSON",
      "Module 2: MongoDB Data Modeling and CRUD Operations\n\nDesigning data models for MongoDB collections\nInserting, updating, and deleting documents\nQuerying and retrieving data using MongoDB queries",
      "Module 3: Advanced MongoDB Queries and Aggregation Framework\n\nComplex queries and query optimization\nAggregation pipeline for advanced data processing\nIndexing strategies for improved query performance",
      "Module 4: MongoDB and Node.js Integration\n\nConnecting MongoDB with Node.js applications\nUsing MongoDB drivers and libraries for Node.js\nBuilding RESTful APIs with MongoDB and Node.js",
      "Module 5: Introduction to Firebase and Real-Time Database\n\nOverview of Firebase and its features\nReal-Time data synchronization with Firebase\nManaging data with Firebase Real-Time Database",
      "Module 6: Firebase Authentication and User Management\n\nUser authentication and authorization with Firebase\nIntegrating Firebase Authentication into applications\nManaging user accounts and permissions",
      "Module 7: Firebase Cloud Firestore and Data Modeling\n\nIntroduction to Firebase Cloud Firestore\nStructuring data in Firestore collections and documents\nQuerying and retrieving data from Firestore",
      "Module 8: Firebase Cloud Functions and Serverless Computing\n\nIntroduction to Firebase Cloud Functions\nImplementing serverless functions with Firebase\nIntegrating functions with database operations",
      "Module 9: Firebase Cloud Storage and File Management\n\nStoring and retrieving files with Firebase Cloud Storage\nUploading and downloading files in Firebase\nManaging file metadata and access permissions",
      "Module 10: Firebase Hosting and Deployment\n\nHosting web applications with Firebase Hosting\nDeploying Firebase applications to the cloud\nConfiguring custom domains and SSL certificates",
      "Module 11: Case Studies and Projects\n\nHands-on projects and exercises using MongoDB and Firebase\nReal-world case studies showcasing practical data management scenarios",
    ],
    Tutors: "Mehaboob Basha, Tere Nagendra Babu, Dharma, Parth",
    Students: "30",
  },
];

export default proj;
